drop function if exists photos.mt_immutable_timestamp(text);
drop function if exists photos.mt_immutable_timestamptz(text);
drop function if exists photos.mt_grams_vector();
drop function if exists photos.mt_grams_query();
drop function if exists photos.mt_grams_array(text);
DROP TABLE IF EXISTS photos.mt_doc_applicationconfiguration CASCADE;
drop function if exists photos.mt_upsert_applicationconfiguration(JSONB, varchar, uuid, uuid);
drop function if exists photos.mt_insert_applicationconfiguration(JSONB, varchar, uuid, uuid);
drop function if exists photos.mt_update_applicationconfiguration(JSONB, varchar, uuid, uuid);
DROP TABLE IF EXISTS photos.mt_doc_deadletterevent CASCADE;
drop function if exists photos.mt_upsert_deadletterevent(JSONB, varchar, uuid, uuid);
drop function if exists photos.mt_insert_deadletterevent(JSONB, varchar, uuid, uuid);
drop function if exists photos.mt_update_deadletterevent(JSONB, varchar, uuid, uuid);
DROP TABLE IF EXISTS photos.mt_doc_objectproperties CASCADE;
drop function if exists photos.mt_upsert_objectproperties(uuid, JSONB, varchar, varchar, uuid);
drop function if exists photos.mt_insert_objectproperties(uuid, JSONB, varchar, varchar, uuid);
drop function if exists photos.mt_update_objectproperties(uuid, JSONB, varchar, varchar, uuid);
DROP TABLE IF EXISTS photos.mt_doc_user CASCADE;
drop function if exists photos.mt_upsert_user(JSONB, varchar, uuid, uuid);
drop function if exists photos.mt_insert_user(JSONB, varchar, uuid, uuid);
drop function if exists photos.mt_update_user(JSONB, varchar, uuid, uuid);
DROP TABLE IF EXISTS photos.mt_streams CASCADE;
DROP TABLE IF EXISTS photos.mt_events CASCADE;
DROP SEQUENCE IF EXISTS photos.mt_events_sequence;
DROP TABLE IF EXISTS photos.mt_event_progression CASCADE;
drop function if exists photos.mt_mark_event_progression(varchar, bigint);
drop function if exists photos.mt_archive_stream(uuid);
DROP SCHEMA IF EXISTS photos CASCADE;