on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git version
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: "5.x"
      - name: Run git version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Test
        env:
          TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
        run: dotnet test --no-build --verbosity normal

      - name: Build docker image
        run: dotnet publish --os linux --arch x64 -c Release -p:ContainerImageTag=$(steps.gitversion.outputs.SemVer) -p:AssemblyVersion=$(steps.gitversion.outputs.MajorMinorPatch) -p:Version=$(steps.gitversion.outputs.SemVer)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB }}
        
      - name: "Push Docker image"
        run: docker push scalefocusad/photopixels-backend-net:$(steps.gitversion.outputs.SemVer)

      - name: Start containers
        env:
          IMAGE_VERSION: $(steps.gitversion.outputs.SemVer)
        run: docker-compose -f "/home/photopixeladmin/docker-containers/dev2.photopixels.io" up -d
