# --------------------------------------------------------------------------------------------------
# This GitHub Actions workflow file is used to automate the build process for the PhotoPixels
# .NET-based backend project. 
#
# Note: The specific jobs and steps may evolve over time as the project requirements change.
# --------------------------------------------------------------------------------------------------

name: dotNET CI for PRs
run-name: ${{ github.actor }} started the .NET CI for PRs workflow

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo ${{github.head_ref}}
          echo ${{github.ref_name}}
          echo ${{github.ref}}
          echo ${{github.path}}

      # - uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      #     submodules: "recursive"

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: 8.0.x

      # - name: Restore dependencies
      #   run: dotnet restore

      # - name: Build project
      #   run: dotnet build

      # - name: Test
      #   run: dotnet test --no-build --verbosity normal --filter "Category!=Integration"
