name: PR build with automated tests
run-name: ${{ github.actor }} started the .NET CI for PRs workflow

on:
  pull_request:
    branches: [ "main", "develop" ]


jobs:
  automated-tests:
    uses: scalefocus/photopixels-automation/.github/workflows/be-tests.yml@main
    with:
      branch: ${{ github.head_ref }}
  
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Test
        run: dotnet test --no-build --verbosity normal --filter "Category!=Integration"

